---
# stop any running beacon/validator docker image
- import_playbook: tasks/stop_beacon.yml
- import_playbook: tasks/stop_validator.yml

# stars beacon node docker container
- import_playbook: tasks/start_beacon.yml

# stars validator docker container
- import_playbook: tasks/start_validator.yml
  when: separate_validator_process_enabled
